spring.profiles.active=local

# Server
server.port=8080
server.servlet.context-path=/QuickScreen

# MySQL driver (same everywhere)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Multipart allow large video chunks (up to 200 MB per chunk)
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB

# Admin credentials
admin.username=admin
admin.password=azaLio@2002-18-06

# JWT used for exam invite links
jwt.secret=QuickScreen@ExamSecret#2026

#simulate in local
verbal.api-url=http://localhost:8080/QuickScreen/api/simulate/verbal-evaluate
verbal.webhook-secret=QuickScreenVerbal#2026

#verbal.api-url=http://localhost:8001/grade-verbal
verbal.callback-url=https://hr-orbit.azalio.io/QuickScreen/api/result/verbal-update
verbal.thread-pool-size=30